baseurl = "https://martantoine.github.io/"
languageCode = "en-us"
theme = "dream"

# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
  noClasses = false
[markup.goldmark.renderer]
  unsafe = true


[params]
  lightTheme = "emerald"
  darkTheme = "forest"
  author = "Antoine Martin"
  avatar = "me.JPG"

  description = "The life record of g1eny0ung is presented here."
  headerTitle = "Antoine Martin's Blog"
  #motto = "Not all those wander are lost J.R.R. Tolkien"

  zenMode = false

  stickyNav = true

  showTableOfContents = true
  showSummaryCoverInPost = true
  imageZoomableInPost = true
  showPrevNextPost = true
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  # contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  # showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false